version: '3.7'

services:

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "6831:6831/udp"
      - "16686:16686"

  rabbitmq:
    image: 'docker.io/bitnami/rabbitmq:3.8-debian-10'
    ports:
      - '4369:4369'
      - '5672:5672'
      - '25672:25672'
      - '15672:15672'
    volumes:
      - 'rabbitmq_data:/bitnami'

  cartdb:
   image: redis:6.2-alpine
   ports:
   - 6379:6379

  inventorydb:
   image: mongo:4.4-bionic
   ports:
   - 27017:27017

  kongdb:
    image: docker.io/bitnami/postgresql:11-debian-10
    volumes:
      - postgresql_data:/bitnami/postgresql
    environment:
      - POSTGRESQL_USERNAME=kong
      - POSTGRESQL_PASSWORD=bitnami
      - POSTGRESQL_DATABASE=kong
  kong:
    image: docker.io/bitnami/kong:2-debian-10
    ports:
      - 8000:8000
      - 8443:8443
    environment:
      - KONG_MIGRATE=yes
      - KONG_PG_HOST=kongdb
      - KONG_PG_PASSWORD=bitnami

  konga:
      image: pantsel/konga
      environment:
        TOKEN_SECRET: some-secret-token
        DB_ADAPTER: postgres
        DB_HOST: kongdb
        DB_PORT: 8000
        DB_DATABASE: kong
        DB_USER: kong
        DB_PASSWORD: bitnami
        NODE_ENV: production
        KONGA_HOOK_TIMEOUT: 10000
      restart: on-failure
      ports:
      - 9000:1337
      depends_on:
      - kongdb

volumes:
  rabbitmq_data:
    driver: local
  postgresql_data:
    driver: local